version: 2
jobs:
  build:
    docker:
      - image: gebish/ci:v7
    environment:
      GRADLE_OPTS: -Xmx1024m -XX:MaxMetaspaceSize=256m
      GRADLE_USER_HOME: .gradle-home
    steps:
      - checkout
      - restore_cache:
          keys:
            - gradle-home
      - run: sudo apt-get --only-upgrade install google-chrome-stable
      - run:
          command: |
            Xvfb :99 -screen 1 1280x1024x16 -nolisten tcp -fbdir /var/run > /dev/null 2>&1 &
            export DISPLAY=:99
            ./gradlew chromeHeadless
      - run:
          name: Save test results
          command: |
            mkdir -p ~/test-results/junit/
            find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} ~/test-results/junit/ \;
          when: always
      - store_test_results:
          path: ~/test-results
      - store_artifacts:
          path: build/reports
      - save_cache:
          key: gradle-home
          paths:
            - .gradle-home